# Checkpoint Three: Cleaning Data

Now you are ready to clean your data. Before starting coding, provide the link to your dataset below.

My dataset:

Import the necessary libraries and create your dataframe(s).

In [241]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bgg_recent_data = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\boardgames_ranks.csv'
bgg_2023_data = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\bgg_GameItem.csv'
bgg_theme = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\bgg_Category.csv'
corrected = r'C:\Users\willm\Desktop\launchcode\cleaning-data-checkpoint\bggdata2023\mismatched.csv'

def reimport_csv(filepath):
    return pd.read_csv(filepath)

df = reimport_csv(bgg_recent_data)
df_supplement = reimport_csv(bgg_2023_data)
df_theme = reimport_csv(bgg_theme)

pd.set_option('Display.max_rows', 20)
df.loc[df['rank'] == 0, 'rank'] = np.nan
df = df.sort_values('rank', ascending=True, na_position = 'last')

display(df)

,id,name,yearpublished,rank,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1,161936,Pandemic Legacy: Season 1,2015,2.0,8.37588,8.52495,54127,0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN
2,174430,Gloomhaven,2017,3.0,8.34433,8.58029,63087,0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN
3,342942,Ark Nova,2021,4.0,8.33919,8.53481,46249,0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
4,233078,Twilight Imperium: Fourth Edition,2017,5.0,8.23688,8.59290,24522,0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158758,430694,Zwai,2025,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Missing Data

Test your dataset for missing data and handle it as needed. Make notes in the form of code comments as to your thought process.

In [242]:
# Almost all of BGG's data is user provided. As such, games which have fewer players often have less data.
# If a game does not have many user reviews/ratings, BGG will not rank it. This prevents games which no one
# has played from becoming the last ranked games on the site. Therefore there are MANY games with a rank of
# NaN. Similarly, because people have not submitted information, there will be NaN values for such columns
# as 'min_players_rec' or 'complexity'. I can't replace that information, because I don't have the information.
# Nor can I drop it, because it doesn't mean the rest of the data is invalid.

display(df.isna().sum())
display(df_supplement.isna().sum())

id                          0
name                        0
yearpublished               0
rank                   131522
bayesaverage                0
average                     0
usersrated                  0
is_expansion                0
abstracts_rank         157343
cgs_rank               158401
childrensgames_rank    157690
familygames_rank       155449
partygames_rank        157852
strategygames_rank     155773
thematic_rank          157093
wargames_rank          154456
dtype: int64

bgg_id               0
name                 0
year              9685
game_type        88074
designer         18251
                 ...
dbpedia_id      113904
luding_id       113904
spielen_id      113904
wikidata_id     113904
wikipedia_id    113904
Length: 38, dtype: int64

In [243]:
# The dataset is missing some data from 2023. I've taken recent data from BoardGameGeek and merged it with the data that contains the category information.

df_merged = pd.merge(df, df_supplement, how="left", left_on='id', right_on='bgg_id')
df_merged = df_merged.sort_values('rank_x', ascending=True, na_position='last')


# This next section I was just using to keep the dataset from crashing my computer when looking at large sections. 
# I'm leaving it in because it's a pain to type all this out again, and I might need it.


# df_merged = df_merged[['id',
#     'name_x',
#     'yearpublished',
#     'rank_x',
#     'bayesaverage',
#     'average',
#     'usersrated',
#     'is_expansion',
#     'abstracts_rank',
#     'cgs_rank',
#     'childrensgames_rank',
#     'familygames_rank',
#     'partygames_rank',
#     'strategygames_rank',
#     'thematic_rank',
#     'wargames_rank',
#     'bgg_id',
#     'name_y',
#     'year',
#     'game_type',
#     'designer',
#     'artist',
#     'publisher',
#     'min_players',
#     'max_players',
#     'min_players_rec',
#     'max_players_rec',
#     'min_players_best',
#     'max_players_best',
#     'min_age',
#     'min_age_rec',
#     'min_time',
#     'max_time',
#     'category',
#     'mechanic',
#     'cooperative',
#     'rank_y'
#     'compilation',
#     'compilation_of',
#     'family',
#     'implementation',
#     'integration',
#     'complexity',
#     'language_dependency',
#     'bga_id',
#     'dbpedia_id',
#     'luding_id',
#     'spielen_id',
#     'wikidata_id',
#     'wikipedia_id'
#     ]]


pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', None)

display(df_merged)

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank,bgg_id,name_y,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,min_time,max_time,category,mechanic,cooperative,compilation,compilation_of,family,implementation,integration,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",2.0,4.0,2.0,4.0,3.0,4.0,14.0,13.825758,60.0,120.0,"1021,1088,2710,1034,1011","2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,NaN,NaN,"17519,65191,14759,8374,22135,77349,70948,26397...",28720,NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955,1.023810,NaN,NaN,NaN,NaN,NaN,NaN
1,161936,Pandemic Legacy: Season 1,2015,2.0,8.37588,8.52495,54127,0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,161936.0,Pandemic Legacy: Season 1,2015.0,"5496,5497","442,378",14057,"538,15889,2366,5657,8820,1391,15983,8291,5812,...",2.0,4.0,2.0,4.0,4.0,4.0,13.0,11.760000,60.0,60.0,"1084,2145","2001,2023,2040,2824,2078,2822,2004,3100,2008,2015",1.0,NaN,NaN,"64952,65191,3430,24281,25404,61854,72224,78680...",30549,NaN,2.0,50631.0,8.53562,1.60680,8.38972,2.8318,4.085938,NaN,NaN,NaN,NaN,NaN,NaN
2,174430,Gloomhaven,2017,3.0,8.34433,8.58029,63087,0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN,174430.0,Gloomhaven,2017.0,"5496,5497",69802,"77084,78961,84269","27425,4304,46179,3475,22380,15605,40478,8820,1...",1.0,4.0,1.0,4.0,3.0,3.0,14.0,13.602113,60.0,120.0,"1022,1020,1010,1046,1047","2689,2839,2018,2857,2893,2023,2854,3004,2676,2...",1.0,NaN,NaN,"59218,25158,65191,66335,68438,7005,5615,8374,7...",NaN,"295770,291457",3.0,58418.0,8.62311,1.75165,8.38865,3.8959,4.166667,NaN,NaN,NaN,NaN,NaN,NaN
3,342942,Ark Nova,2021,4.0,8.33919,8.53481,46249,0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,342942.0,Ark Nova,2021.0,5497,138517,"138547,11462,12484,11797","22380,30958,21608,10768,12540,8820,42325,17179...",1.0,4.0,1.0,3.0,2.0,2.0,14.0,12.442623,90.0,150.0,"1089,1021,1084","2875,2040,2026,2902,2914,2041,2004,2819,3100,2...",NaN,NaN,NaN,"67874,70360,73596,76649,5666,68335,66167,76846",NaN,NaN,4.0,31052.0,8.53405,1.38518,8.30236,3.7249,3.712121,NaN,NaN,NaN,NaN,NaN,NaN
4,233078,Twilight Imperium: Fourth Edition,2017,5.0,8.23688,8.59290,24522,0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN,233078.0,Twilight Imperium: Fourth Edition,2017.0,"5496,5497","96049,6651,21",11988,"17,23043,3475,157,15889,2973,4617,15605,18852,...",3.0,6.0,3.0,6.0,6.0,6.0,14.0,14.135135,240.0,480.0,"1015,1021,1020,1026,1001,1016,1113,1019","2838,2080,2021,2072,2843,2676,2026,2914,2886,2...",NaN,NaN,NaN,"67874,64949,25158,29,12210,78680",12493,NaN,5.0,20922.0,8.61973,1.61439,8.24243,4.3080,4.093750,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158758,430694,Zwai,2025,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [244]:
# Now I take the merged datasets and I look for any which have a name and rank in the old dataset, but not in the new dataset. 
# I'll also filter it to just those games published before 2024. These are limitations, but given the timescale of the project I do not have unlimited time to clean the data.

mismatched = df_merged[(df_merged['name_x'].notna()) & (df_merged['name_y'].isna())  & (df_merged['rank_x'].notna()) & (df_merged['yearpublished'] < 2024)]
pd.set_option('display.max_rows', 20)
display(mismatched)

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank,bgg_id,name_y,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,min_time,max_time,category,mechanic,cooperative,compilation,compilation_of,family,implementation,integration,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
33,397598,Dune: Imperium – Uprising,2023,34.0,7.85624,8.73729,6843,0,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,396790,Nucleum,2023,202.0,7.33697,8.19123,4997,0,NaN,NaN,NaN,NaN,NaN,113.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,391163,Forest Shuffle,2023,312.0,7.17070,7.64585,8475,0,NaN,NaN,NaN,56.0,NaN,218.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
378,400314,Apiary,2023,379.0,7.09694,7.82910,5173,0,NaN,NaN,NaN,NaN,NaN,231.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1420,397385,Pirates of Maracaibo,2023,1421.0,6.41814,8.01954,1243,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24911,72630,Smart Ass: The Card Game,2009,24912.0,5.48655,5.21011,91,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25413,399757,Linx,2023,25414.0,5.48170,5.41925,255,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25855,400859,The way to Juliet,0,25856.0,5.47526,4.51154,52,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26655,404427,Mensch ärgere Dich nicht,1910,26656.0,5.44942,3.83889,72,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26870,395847,Space Marine: The Board Game,2023,26871.0,5.42774,3.44595,74,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4295.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [245]:
# Outside of this file I created my own csv. I then filled in the category information for each value. 
# Now I will reimport the data, and merge it with my dataset, giving me categories for the data I was missing.

# mismatched.to_csv('mismatched.csv', index=False)

corrected_data = reimport_csv(corrected)
df_merged.loc[df_merged['id'].isin(corrected_data['id']), 'category'] = df_merged['id'].map(corrected_data.set_index('id')['category'])
df_merged['category'] = df_merged['category'].apply(lambda x: x if isinstance(x, list) else (x.split(',') if isinstance(x,str) else np.nan))


df_exploded = df_merged.explode('category')
df_grouped = df_exploded.groupby(['year','category']).size().reset_index(name='count')

In [246]:
# I'll also define some smaller datasets which will be useful later on.
df_filtered = df_merged[df_merged['rank_x'].notna()]

df_filtered_small = df_merged[df_merged['rank_x'] <= 2000]

df_exploded = df_merged.explode('category')
df_grouped = df_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_grouped = df_filtered_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_grouped = df_fs_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

## Irregular Data

Detect outliers in your dataset and handle them as needed. Use code comments to make notes about your thought process.

In [247]:
# We'll start with the smallest dataset. Luckily there don't appear to be any duplicates.
pd.set_option('display.max_rows', None)
df_fs_dup_rank = df_filtered_small[(df_filtered_small['rank_x'].duplicated('keep'==False) == True)][['id', 'name_x', 'rank_x']]
display(df_fs_dup_rank)

df_fs_dup_id = df_filtered_small[(df_filtered_small['id'].duplicated('keep'==False) == True)][['id', 'name_x', 'rank_x']]
display(df_fs_dup_id)


# There don't seem to be any duplicates for the group of ranked games either. BoardGameGeek is very good at data handling.
pd.set_option('display.max_rows', 50)
df_filtered_dup_rank = df_filtered[(df_filtered['rank_x'].duplicated('keep'==False) == True)][['id', 'name_x', 'rank_x']]
display(df_filtered_dup_rank)

df_filtered_dup_id = df_filtered[(df_filtered['id'].duplicated('keep'==False) == True)][['id', 'name_x', 'rank_x']]
display(df_filtered_dup_id)

# For the final group we can't look for duplicate ranks because lots of them have NaN as a value. We'll just look for duplicate ids.
df_merged_dup_id = df_merged[(df_merged['id'].duplicated('keep'==False) == True)][['id', 'name_x', 'rank_x']]
display(df_merged_dup_id)


# Now we'll look for anything that's impossible, such as average rank higher than 10. I'll also drop a few things I know are in the dataset but not technically possible, such as games that "were released" in 2025.

super_rank = df_merged[df_merged['average'] > 10][['id', 'name_x', 'rank_x']]
display(super_rank)

display(df_merged[df_merged['yearpublished'] == 2025])
df_merged = df_merged[df_merged['yearpublished'] != 2025]

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

Empty DataFrame
Columns: [id, name_x, rank_x]
Index: []

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank,bgg_id,name_y,year,game_type,designer,artist,publisher,min_players,max_players,min_players_rec,max_players_rec,min_players_best,max_players_best,min_age,min_age_rec,min_time,max_time,category,mechanic,cooperative,compilation,compilation_of,family,implementation,integration,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity,language_dependency,bga_id,dbpedia_id,luding_id,spielen_id,wikidata_id,wikipedia_id
5136,391137,Galactic Cruise,2025,5137.0,5.74262,8.24556,247,0,NaN,NaN,NaN,NaN,NaN,1894.0,NaN,NaN,391137.0,Galactic Cruise,2024.0,NaN,"129131,154241,128912",64844,46278,1.0,4.0,1.0,4.0,1.0,4.0,14.0,NaN,90.0,150.0,"[2650, 1021, 1088, 1016, 1113]","2001,2883,2875,2040,2902,2900,2011,3099,2041,2...",NaN,NaN,NaN,"8374,73596,5666,19298",NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.6667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5173,392492,Stupor Mundi,2025,5174.0,5.74060,7.35952,336,0,NaN,NaN,NaN,NaN,NaN,1870.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7614,371330,Luthier,2025,7615.0,5.62428,8.08555,124,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371330.0,Luthier,2024.0,NaN,"122780,25037",12130,46707,1.0,4.0,1.0,4.0,1.0,4.0,14.0,NaN,60.0,120.0,"[1088, 1054, 1070]","2012,2082,2933",NaN,NaN,NaN,"22184,50153,8374,55085,28718",NaN,NaN,NaN,7.0,9.14286,0.590054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7719,375459,Speakeasy,2025,7720.0,5.62127,8.52345,115,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,375459.0,Speakeasy,NaN,NaN,12396,NaN,597,2.0,4.0,2.0,4.0,2.0,4.0,16.0,NaN,NaN,NaN,"[1021, 1088, 1033, 1086]","2080,2040,2007",NaN,NaN,NaN,"22184,73776,65600",NaN,NaN,NaN,5.0,9.60000,0.489898,NaN,4.3333,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8966,274471,Malhya: Lands of Legends,2025,8967.0,5.59313,9.19576,165,0,NaN,NaN,NaN,NaN,NaN,NaN,1235.0,NaN,274471.0,Malhya: Lands of Legends,2023.0,5496,"116120,116118,116119,77482",77482,"41717,27121",1.0,5.0,1.0,5.0,1.0,5.0,14.0,NaN,60.0,180.0,"[1022, 1020, 1010, 1046, 1047]","2023,3002,2072,2676,2011,2661,2028,2020,2819,2...",1.0,NaN,NaN,"22783,22184,59218,25158,8374,24281",NaN,NaN,8753.0,138.0,9.21594,1.406260,5.58347,3.4167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158752,430680,Cloudspire: The Graft – Faction Expansion,2025,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158753,430681,Cloudspire: Keel – Faction Expansion,2025,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158754,430682,Cloudspire: Shada – Faction Expansion,2025,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158755,430683,20 Strong: Cloudspire,2025,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158758,430694,Zwai,2025,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Unnecessary Data

Look for the different types of unnecessary data in your dataset and address it as needed. Make sure to use code comments to illustrate your thought process.

In [248]:
# I will drop those columns which will be fairly irrelevant to the particular analysis I want to perform.
# It is possible this data would be useful for further analysis of other questions.
# For example, what themes are most popular for solo games?

df_merged.drop([
#     'id',
#     'name_x',
#     'yearpublished',
#     'rank_x',
#     'bayesaverage',
#     'average',
#     'usersrated',
    'is_expansion',
    'abstracts_rank',
    'cgs_rank',
    'childrensgames_rank',
    'familygames_rank',
    'partygames_rank',
    'strategygames_rank',
    'thematic_rank',
    'wargames_rank',
#     'bgg_id',
#     'name_y',
#     'year',
#     'game_type',
#     'designer',
#     'artist',
#     'publisher',
    'min_players',
    'max_players',
    'min_players_rec',
    'max_players_rec',
    'min_players_best',
    'max_players_best',
    'min_age',
    'min_age_rec',
    'min_time',
    'max_time',
#     'category',
#     'mechanic',
#     'cooperative',
#     'rank_y'
    'compilation',
    'compilation_of',
    'family',
    'implementation',
    'integration',
#     'complexity',
    'language_dependency',
    'bga_id',
    'dbpedia_id',
    'luding_id',
    'spielen_id',
    'wikidata_id',
    'wikipedia_id'
    ], axis=1, inplace=True)

display(df_merged)

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,bgg_id,name_y,year,game_type,designer,artist,publisher,category,mechanic,cooperative,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...","[1021, 1088, 2710, 1034, 1011]","2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
1,161936,Pandemic Legacy: Season 1,2015,2.0,8.37588,8.52495,54127,161936.0,Pandemic Legacy: Season 1,2015.0,"5496,5497","442,378",14057,"538,15889,2366,5657,8820,1391,15983,8291,5812,...","[1084, 2145]","2001,2023,2040,2824,2078,2822,2004,3100,2008,2015",1.0,2.0,50631.0,8.53562,1.60680,8.38972,2.8318
2,174430,Gloomhaven,2017,3.0,8.34433,8.58029,63087,174430.0,Gloomhaven,2017.0,"5496,5497",69802,"77084,78961,84269","27425,4304,46179,3475,22380,15605,40478,8820,1...","[1022, 1020, 1010, 1046, 1047]","2689,2839,2018,2857,2893,2023,2854,3004,2676,2...",1.0,3.0,58418.0,8.62311,1.75165,8.38865,3.8959
3,342942,Ark Nova,2021,4.0,8.33919,8.53481,46249,342942.0,Ark Nova,2021.0,5497,138517,"138547,11462,12484,11797","22380,30958,21608,10768,12540,8820,42325,17179...","[1089, 1021, 1084]","2875,2040,2026,2902,2914,2041,2004,2819,3100,2...",NaN,4.0,31052.0,8.53405,1.38518,8.30236,3.7249
4,233078,Twilight Imperium: Fourth Edition,2017,5.0,8.23688,8.59290,24522,233078.0,Twilight Imperium: Fourth Edition,2017.0,"5496,5497","96049,6651,21",11988,"17,23043,3475,157,15889,2973,4617,15605,18852,...","[1015, 1021, 1020, 1026, 1001, 1016, 1113, 1019]","2838,2080,2021,2072,2843,2676,2026,2914,2886,2...",NaN,5.0,20922.0,8.61973,1.61439,8.24243,4.3080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158757,430692,Hidden Games Tatort: Campingkiller,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [256]:
# I reapply the theme mapping.

df_exploded = df_merged.explode('category')

theme_map = df_theme.set_index('bgg_id')['name'].to_dict()

def map_id_to_theme(theme_ids):
    if pd.isna(theme_ids):
        return theme_ids
    ids = theme_ids.split(',')
    names = [theme_map.get(int(cat_id.strip()), 'Unknown') for cat_id in ids]
    return names

# I have to convert the lists into strings in order to look for unique values in the 'category' column.
df_exploded['category'] = df_exploded['category'].apply(map_id_to_theme)
df_exploded['category'] = df_exploded['category'].apply(lambda x: x[0] if isinstance(x, list) and len(x) == 1 else x)
display(df_exploded)

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,bgg_id,name_y,year,game_type,designer,artist,publisher,category,mechanic,cooperative,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Economic,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.4233,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Industry / Manufacturing,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.4233,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Post-Napoleonic,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.4233,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Trains,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.4233,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Transportation,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.4233,3.8955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158757,430692,Hidden Games Tatort: Campingkiller,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,0.00000,0.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [259]:
# Here I am re-defining the filtered, small filtered, grouped and exploded datasets with the pared down beginning dataframe.
df_filtered = df_merged[df_merged['rank_x'].notna()]

df_filtered_small = df_merged[df_merged['rank_x'] <= 2000]

df_grouped = df_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_exploded['category'] = df_filtered_exploded['category'].apply(map_id_to_theme)
df_filtered_exploded['category'] = df_filtered_exploded['category'].apply(lambda x: x[0] if isinstance(x, list) and len(x) == 1 else x)
df_filtered_grouped = df_filtered_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_exploded['category'] = df_fs_exploded['category'].apply(map_id_to_theme)
df_fs_exploded['category'] = df_fs_exploded['category'].apply(lambda x: x[0] if isinstance(x, list) and len(x) == 1 else x)
df_fs_grouped = df_fs_exploded.groupby(['yearpublished','category']).size().reset_index(name='count')

In [261]:
display(df_filtered_exploded)

,id,name_x,yearpublished,rank_x,bayesaverage,average,usersrated,bgg_id,name_y,year,game_type,designer,artist,publisher,category,mechanic,cooperative,rank_y,num_votes,avg_rating,stddev_rating,bayes_rating,complexity
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Economic,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Industry / Manufacturing,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Post-Napoleonic,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Trains,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,224517.0,Brass: Birmingham,2018.0,5497,"32887,32943,6","70571,70568,38179","21765,3475,25074,21608,11043,34522,31071,8832,...",Transportation,"2040,2902,2904,2900,2081,3100,2849,2826,2897",NaN,1.0,38651.0,8.61232,1.42368,8.42330,3.8955
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27239,5432,Chutes and Ladders,-200,27240.0,3.66187,2.90782,4793,5432.0,Chutes and Ladders,-200.0,4665,3,"52810,71033,8810,63030,10171,6710,141083,9988,...","171,20,1001,2008,1017,10814,30,690,4680,7548,2...",Children's Game,"2850,2876,2035,2939",NaN,24222.0,4412.0,2.89101,1.66474,3.64057,1.0305
27239,5432,Chutes and Ladders,-200,27240.0,3.66187,2.90782,4793,5432.0,Chutes and Ladders,-200.0,4665,3,"52810,71033,8810,63030,10171,6710,141083,9988,...","171,20,1001,2008,1017,10814,30,690,4680,7548,2...",Movies / TV / Radio theme,"2850,2876,2035,2939",NaN,24222.0,4412.0,2.89101,1.66474,3.64057,1.0305
27239,5432,Chutes and Ladders,-200,27240.0,3.66187,2.90782,4793,5432.0,Chutes and Ladders,-200.0,4665,3,"52810,71033,8810,63030,10171,6710,141083,9988,...","171,20,1001,2008,1017,10814,30,690,4680,7548,2...",World War II,"2850,2876,2035,2939",NaN,24222.0,4412.0,2.89101,1.66474,3.64057,1.0305
27240,11901,Tic-Tac-Toe,-1300,27241.0,3.65364,2.74315,4021,11901.0,Tic-Tac-Toe,-1300.0,"4665,4666",3,NaN,"171,3320,1017,6514,33079,225,5314,2401,18726,1...",Abstract Strategy,"2055,2048,2940",NaN,24230.0,3724.0,2.73514,1.99005,3.62489,1.2874
27240,11901,Tic-Tac-Toe,-1300,27241.0,3.65364,2.74315,4021,11901.0,Tic-Tac-Toe,-1300.0,"4665,4666",3,NaN,"171,3320,1017,6514,33079,225,5314,2401,18726,1...",Children's Game,"2055,2048,2940",NaN,24230.0,3724.0,2.73514,1.99005,3.62489,1.2874

In [262]:
df_exploded['category'].unique()

array(['Economic', 'Industry / Manufacturing', 'Post-Napoleonic',
       'Trains', 'Transportation', 'Environmental', 'Medical',
       'Adventure', 'Exploration', 'Fantasy', 'Fighting', 'Miniatures',
       'Animals', 'Civilization', 'Negotiation', 'Political',
       'Science Fiction', 'Space Exploration', 'Wargame',
       'Movies / TV / Radio theme', 'Novel-based', 'Territory Building',
       'Civil War', 'Mythology', 'Modern Warfare', 'Card Game',
       'American West', 'Dice', 'Medieval', 'Ancient', 'City Building',
       'Horror', 'Farming', 'Puzzle', 'Nautical',
       'Collectible Components', 'Travel', 'Educational', 'Religious',
       'Racing', 'Sports', 'Comic Book / Strip', 'Spies/Secret Agents',
       'Action / Dexterity', 'Murder/Mystery', 'Aviation / Flight',
       'Pirates', 'Bluffing', 'Video Game Theme', 'Mature / Adult',
       'Abstract Strategy', 'Renaissance', 'Arabian', 'Prehistoric',
       'Deduction', 'Party Game', 'Word Game', 'World War II', 'Number',
       nan, 'Pike and Shot', 'Real-time', 'Zombies', 'World War I',
       'Electronic', 'Humor', 'Print & Play', 'Age of Reason', 'Unknown',
       'Math', 'Maze', 'Mafia', 'Napoleonic', "Children's Game",
       'American Indian Wars', 'Vietnam War', 'Memory',
       'Expansion for Base-game', 'American Revolutionary War',
       'American Civil War', 'Music', 'Trivia', 'Korean War',
       'Game System', 'Fan Expansion', 'Book'], dtype=object)

In [263]:
# Here I am removing the 'categories' which I would define as 'mechanics' rather than 'themes'. 
# Unfortunately this is more an opinion than a factual definition,
# but I've done the best I can to select only those categories which I believe are distinct themes.


df_theme_exploded = df_exploded[
    (df_exploded['category'] != 'Card Game') |
    (df_exploded['category'] != 'Bluffing') |
    (df_exploded['category'] != 'Negotiation') |
    (df_exploded['category'] != 'Print & Play') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Action / Dexterity') |
    (df_exploded['category'] != 'Dice') |
    (df_exploded['category'] != 'Collectible Components') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Memory') |
    (df_exploded['category'] != 'Game System')]
df_theme_filtered_exploded = df_filtered_exploded[
    (df_exploded['category'] != 'Card Game') |
    (df_exploded['category'] != 'Bluffing') |
    (df_exploded['category'] != 'Negotiation') |
    (df_exploded['category'] != 'Print & Play') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Action / Dexterity') |
    (df_exploded['category'] != 'Dice') |
    (df_exploded['category'] != 'Collectible Components') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Memory') |
    (df_exploded['category'] != 'Game System')]
df_theme_fs_exploded = df_fs_exploded[
    (df_exploded['category'] != 'Card Game') |
    (df_exploded['category'] != 'Bluffing') |
    (df_exploded['category'] != 'Negotiation') |
    (df_exploded['category'] != 'Print & Play') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Action / Dexterity') |
    (df_exploded['category'] != 'Dice') |
    (df_exploded['category'] != 'Collectible Components') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Memory') |
    (df_exploded['category'] != 'Game System')]

C:\Users\willm\AppData\Local\Temp\ipykernel_21840\2780971971.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_theme_filtered_exploded = df_filtered_exploded[
C:\Users\willm\AppData\Local\Temp\ipykernel_21840\2780971971.py:30: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_theme_fs_exploded = df_fs_exploded[

## Inconsistent Data

Check for inconsistent data and address any that arises. As always, use code comments to illustrate your thought process.

In [255]:
# Unfortunately it's difficult to code for inconsistent data because I spent most of the previous 3 sections removing or changing anything that was inconsistent. 
# A good example was in the last section, where I was required to convert the list format created by my mapping to string format in order to process it.
# I also spent more than half my time on fixing the data in my homemade CSV so that it would read properly. 
# I kept coming across an error where Excel would convert the 'category' values to large numbers and then round them using scientific notation.

## Summarize Your Results

Make note of your answers to the following questions.

1. Did you find all four types of dirty data in your dataset? 

        Oh yes, definitely. I expected that I would come across missing data, and I knew I had a ton of unnecessary data, but the sheer amount of work I had to do to clean inconsistent data was definitely a surprise.

2. Did the process of cleaning your data give you new insights into your dataset?

        It definitely taught me that cleaning the dataset is by far the most work when it comes to data analysis.

3. Is there anything you would like to make note of when it comes to manipulating the data and making visualizations?

    I may come back and tweak which columns I have available. There are all sorts of interesting questions which can be answered with the data I have. For sure I want to be able to filter the data by year in Tableau, rather than create 30 different charts like I did in the EDA section.