# Checkpoint Three: Cleaning Data

Now you are ready to clean your data. Before starting coding, provide the link to your dataset below.

My dataset:

Import the necessary libraries and create your dataframe(s).

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bgg_recent_data = r'C:\Users\willm\Desktop\launchcode\finalproject\boardgames_ranks_2024-10-15\boardgames_ranks.csv'
bgg_2023_data = r'C:\Users\willm\Desktop\launchcode\finalproject\boardgames_ranks_2024-10-15\bgg_GameItem.csv'
bgg_theme = r'C:\Users\willm\Desktop\launchcode\finalproject\boardgames_ranks_2024-10-15\bgg_Category.csv'

def reimport_csv(filepath):
    return pd.read_csv(filepath)

df = reimport_csv(bgg_recent_data)
df_supplement = reimport_csv(bgg_2023_data)
df_theme = reimport_csv(bgg_theme)

df.loc[df['rank'] == 0, 'rank'] = np.nan
df = df.sort_values('rank', ascending=True, na_position = 'last')



display(df)

,id,name,yearpublished,rank,bayesaverage,average,usersrated,is_expansion,abstracts_rank,cgs_rank,childrensgames_rank,familygames_rank,partygames_rank,strategygames_rank,thematic_rank,wargames_rank
0,224517,Brass: Birmingham,2018,1.0,8.41286,8.59193,47904,0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
1,161936,Pandemic Legacy: Season 1,2015,2.0,8.37588,8.52495,54127,0,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN
2,174430,Gloomhaven,2017,3.0,8.34433,8.58029,63087,0,NaN,NaN,NaN,NaN,NaN,4.0,2.0,NaN
3,342942,Ark Nova,2021,4.0,8.33919,8.53481,46249,0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
4,233078,Twilight Imperium: Fourth Edition,2017,5.0,8.23688,8.59290,24522,0,NaN,NaN,NaN,NaN,NaN,5.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158758,430694,Zwai,2025,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,0.00000,0.00000,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,0.00000,0.00000,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
merged_df = pd.merge(df, df_supplement, how="left", left_on='id', right_on='bgg_id')
merged_df = merged_df.sort_values('rank_x', ascending=True)

merged_df = merged_df[['id',
    'name_x',
    'yearpublished',
    'rank_x',
#     'bayesaverage',
#     'average',
#     'usersrated',
#     'is_expansion',
#     'abstracts_rank',
#     'cgs_rank',
#     'childrensgames_rank',
#     'familygames_rank',
#     'partygames_rank',
#     'strategygames_rank',
#     'thematic_rank',
#     'wargames_rank',
    'bgg_id',
    'name_y',
    'year',
#     'game_type',
#     'designer',
#     'artist',
#     'publisher',
#     'min_players',
#     'max_players',
#     'min_players_rec',
#     'max_players_rec',
#     'min_players_best',
#     'max_players_best',
#     'min_age',
#     'min_age_rec',
#     'min_time',
#     'max_time',
    'category',
#     'mechanic',
#     'cooperative',
    'rank_y'
#     'compilation',
#     'compilation_of',
#     'family',
#     'implementation',
#     'integration',
#     'complexity',
#     'language_dependency',
#     'bga_id',
#     'dbpedia_id',
#     'luding_id',
#     'spielen_id',
#     'wikidata_id',
#     'wikipedia_id'
    ]]
# pd.set_option('display.max_rows', 20)
# pd.set_option('display.max_columns', None)

theme_map = df_theme.set_index('bgg_id')['name'].to_dict()

def map_id_to_theme(theme_ids):
    if pd.isna(theme_ids):
        return theme_ids
    ids = theme_ids.split(',')
    names = [theme_map.get(int(cat_id.strip()), 'Unknown') for cat_id in ids]
    return names


merged_df['category'] = merged_df['category'].apply(map_id_to_theme)
pd.set_option('display.max_columns', None)

display(merged_df)

,id,name_x,yearpublished,rank_x,bgg_id,name_y,year,category,rank_y
0,224517,Brass: Birmingham,2018,1.0,224517.0,Brass: Birmingham,2018.0,"[Economic, Industry / Manufacturing, Post-Napo...",1.0
1,161936,Pandemic Legacy: Season 1,2015,2.0,161936.0,Pandemic Legacy: Season 1,2015.0,"[Environmental, Medical]",2.0
2,174430,Gloomhaven,2017,3.0,174430.0,Gloomhaven,2017.0,"[Adventure, Exploration, Fantasy, Fighting, Mi...",3.0
3,342942,Ark Nova,2021,4.0,342942.0,Ark Nova,2021.0,"[Animals, Economic, Environmental]",4.0
4,233078,Twilight Imperium: Fourth Edition,2017,5.0,233078.0,Twilight Imperium: Fourth Edition,2017.0,"[Civilization, Economic, Exploration, Negotiat...",5.0
...,...,...,...,...,...,...,...,...,...
158758,430694,Zwai,2025,NaN,NaN,NaN,NaN,NaN,NaN
158759,430696,King of Tokyo: Gift Promo Cards – Worldwide Se...,2024,NaN,NaN,NaN,NaN,NaN,NaN
158760,430697,Murder On The Moon,2024,NaN,NaN,NaN,NaN,NaN,NaN
158761,430698,Snaptastic,2024,NaN,NaN,NaN,NaN,NaN,NaN
158762,430699,Jungle Hustle,2024,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df_filtered = merged_df[merged_df['rank_y'].notna()]

df_filtered_small = merged_df[merged_df['rank_y'] <= 2000]

In [40]:
df_exploded = merged_df.explode('category')
df_grouped = df_exploded.groupby(['year','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_grouped = df_filtered_exploded.groupby(['year','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_grouped = df_fs_exploded.groupby(['year','category']).size().reset_index(name='count')

## Missing Data

Test your dataset for missing data and handle it as needed. Make notes in the form of code comments as to your thought process.

In [43]:
# Almost all of BGG's data is user provided. As such, games which have fewer players often have less data.
# If a game does not have many user reviews/ratings, BGG will not rank it. This prevents games which no one
# has played from becoming the last ranked games on the site. Therefore there are MANY games with a rank of
# NaN. Similarly, because people have not submitted information, there will be NaN values for such columns
# as 'min_players_rec' or 'complexity'. I can't replace that information, because I don't have the information.
# Nor can I drop it, because it doesn't mean the rest of the data is invalid.

# print(df.isna().sum())

# print(df_filtered.isna().sum())

# print(df_filtered_small.isna().sum())

In [41]:
# The dataset is missing some data from 

mismatched = merged_df[(merged_df['name_x'].notna()) & (merged_df['name_y'].isna())  & (merged_df['rank_x'].notna()) & (merged_df['yearpublished'] < 2024)]
pd.set_option('display.max_rows', None)
display(mismatched.count())

id               279
name_x           279
yearpublished    279
rank_x           279
bgg_id             0
name_y             0
year               0
category           0
rank_y             0
dtype: int64

## Irregular Data

Detect outliers in your dataset and handle them as needed. Use code comments to make notes about your thought process.

In [ ]:
pd.set_option('display.max_rows', None)
df_fs_duplicates = df_filtered_small[(df_filtered_small['rank'].duplicated('keep'==False) == True)][['bgg_id', 'name', 'rank']]
display(df_fs_duplicates)

## Unnecessary Data

Look for the different types of unnecessary data in your dataset and address it as needed. Make sure to use code comments to illustrate your thought process.

In [ ]:
# I will drop those columns which will be fairly irrelevant to the particular analysis I want to perform.
# It is possible this data would be useful for further analysis of other questions.
# For example, what themes are most popular for solo games?

df.drop([
    'min_players',
    'max_players',
    'min_players_rec',
    'max_players_rec',
    'min_players_best',
    'max_players_best',
    'bga_id', 
    'dbpedia_id', 
    'luding_id', 
    'spielen_id', 
    'wikidata_id', 
    'wikipedia_id'], axis=1, inplace=True)

display(df)

In [67]:
# Here I am re-defining the filtered, small filtered, and exploded datasets with the pared down beginning dataframe.
df_filtered = df[df['rank'].notna()]

df_filtered_small = df[df['rank'] <= 2000]

df_exploded = df.explode('category')
df_grouped = df_exploded.groupby(['year','category']).size().reset_index(name='count')

df_filtered_exploded = df_filtered.explode('category')
df_filtered_grouped = df_filtered_exploded.groupby(['year','category']).size().reset_index(name='count')

df_fs_exploded = df_filtered_small.explode('category')
df_fs_grouped = df_fs_exploded.groupby(['year','category']).size().reset_index(name='count')

In [ ]:
# I take the 'exploded' dataframe and look for unique values in the 'category' column.
df_exploded['category'].unique()

In [72]:
# Here I am removing the 'categories' which I would define as 'mechanics' rather than 'themes'. 
# Unfortunately this is more an opinion than a factual definition,
# but I've done the best I can to select only those categories which I believe are distinct themes.


df_theme_exploded = df_exploded[
    (df_exploded['category'] != 'Card Game') |
    (df_exploded['category'] != 'Bluffing') |
    (df_exploded['category'] != 'Print & Play') |
    (df_exploded['category'] != 'Real-time') |
    (df_exploded['category'] != 'Action / Dexterity') |
    (df_exploded['category'] != 'Dice') |
    (df_exploded['category'] != 'Collectible Components')]
df_theme_filtered_exploded = df_filtered_exploded[
    (df_filtered_exploded['category'] != 'Card Game') |
    (df_filtered_exploded['category'] != 'Bluffing') |
    (df_filtered_exploded['category'] != 'Print & Play') |
    (df_filtered_exploded['category'] != 'Real-time') |
    (df_filtered_exploded['category'] != 'Action / Dexterity') |
    (df_filtered_exploded['category'] != 'Dice') |
    (df_filtered_exploded['category'] != 'Collectible Components')]
df_theme_fs_exploded = df_fs_exploded[
    (df_fs_exploded['category'] != 'Card Game') |
    (df_fs_exploded['category'] != 'Bluffing') |
    (df_fs_exploded['category'] != 'Print & Play') |
    (df_fs_exploded['category'] != 'Real-time') |
    (df_fs_exploded['category'] != 'Action / Dexterity') |
    (df_fs_exploded['category'] != 'Dice') |
    (df_fs_exploded['category'] != 'Collectible Components')]

## Inconsistent Data

Check for inconsistent data and address any that arises. As always, use code comments to illustrate your thought process.

## Summarize Your Results

Make note of your answers to the following questions.

1. Did you find all four types of dirty data in your dataset?
2. Did the process of cleaning your data give you new insights into your dataset?
3. Is there anything you would like to make note of when it comes to manipulating the data and making visualizations?